-- File: supabase/seed/05_medical_concerns.sql

-- MEDICAL CHEST
INSERT INTO primary_concerns (id, body_part_id, name_ar, name_en, description_ar, description_en, icon, prevalence, urgency_default, requires_age_context, common_age_ranges, specialty_primary, specialty_secondary) VALUES
('medical_chest_breast_pain', 'medical_chest', 'ألم الثدي', 'Breast Pain', 'ألم أو حساسية في أحد الثديين أو كليهما', 'Pain or tenderness in one or both breasts', '⚠️', 'very_common', 'moderate', TRUE, ARRAY['18-24', '25-34', '35-44', '45+'], 'Gynecology', 'Breast Surgery'),
('medical_chest_breast_lump', 'medical_chest', 'كتلة في الثدي', 'Breast Lump', 'اكتشاف كتلة أو تورم في الثدي', 'Discovery of a lump or mass in the breast', '🔴', 'common', 'urgent', TRUE, ARRAY['25-34', '35-44', '45+'], 'Gynecology', 'Oncology'),
('medical_chest_nipple_discharge', 'medical_chest', 'إفرازات من الحلمة', 'Nipple Discharge', 'خروج سوائل من الحلمة بدون حمل أو رضاعة', 'Fluid discharge from nipple when not pregnant or breastfeeding', '💧', 'common', 'moderate', TRUE, ARRAY['18-24', '25-34', '35-44'], 'Gynecology', 'Endocrinology'),
('medical_chest_breastfeeding', 'medical_chest', 'مشاكل الرضاعة الطبيعية', 'Breastfeeding Difficulties', 'صعوبات في الرضاعة الطبيعية', 'Challenges with nursing or milk production', '🤱', 'very_common', 'routine', TRUE, ARRAY['25-34', '35-44'], 'Lactation Consultant', 'Gynecology'),
('medical_chest_cardiac', 'medical_chest', 'ألم في الصدر', 'Chest Pain', 'ألم أو ضيق في منطقة الصدر', 'Pain or tightness in the chest area', '💔', 'common', 'urgent', FALSE, ARRAY['35-44', '45+'], 'Cardiology', 'Internal Medicine'),
('medical_chest_breathing', 'medical_chest', 'صعوبة في التنفس', 'Breathing Difficulty', 'ضيق في التنفس أو صعوبة في أخذ نفس عميق', 'Shortness of breath or difficulty taking deep breaths', '🫁', 'common', 'urgent', FALSE, ARRAY['18-24', '25-34', '35-44', '45+'], 'Pulmonology', 'Cardiology'),
('medical_chest_cough', 'medical_chest', 'سعال مستمر', 'Persistent Cough', 'سعال لم يتحسن منذ أسبوعين أو أكثر', 'Cough lasting two weeks or longer', '😷', 'very_common', 'routine', FALSE, ARRAY['18-24', '25-34', '35-44', '45+'], 'Pulmonology', 'Internal Medicine')
ON CONFLICT (id) DO NOTHING;

INSERT INTO symptoms (id, concern_id, name_ar, name_en, description_ar, description_en, icon, severity_indicator, is_red_flag) VALUES
('symptom_breast_pain_cyclic', 'medical_chest_breast_pain', 'ألم يرتبط بالدورة الشهرية', 'Pain related to menstrual cycle', 'يزداد الألم قبل الدورة الشهرية ويخف بعدها', 'Pain increases before period and decreases after', '📅', 'mild', FALSE),
('symptom_breast_pain_constant', 'medical_chest_breast_pain', 'ألم مستمر', 'Constant pain', 'ألم موجود طوال الوقت بغض النظر عن الدورة', 'Pain present all the time regardless of cycle', '⏰', 'moderate', TRUE),
('symptom_breast_pain_sharp', 'medical_chest_breast_pain', 'ألم حاد أو طاعن', 'Sharp or stabbing pain', 'ألم مفاجئ وحاد كالطعنات', 'Sudden, sharp pain like being stabbed', '⚡', 'severe', TRUE),
('symptom_breast_pain_both', 'medical_chest_breast_pain', 'ألم في كلا الثديين', 'Pain in both breasts', 'الألم موجود في الثديين معاً', 'Pain present in both breasts', '↔️', 'mild', FALSE),
('symptom_breast_pain_one', 'medical_chest_breast_pain', 'ألم في ثدي واحد فقط', 'Pain in one breast only', 'الألم في جهة واحدة فقط', 'Pain on one side only', '➡️', 'moderate', TRUE),
('symptom_breast_pain_warmth', 'medical_chest_breast_pain', 'احمرار أو سخونة', 'Redness or warmth', 'المنطقة المؤلمة حمراء أو ساخنة', 'Painful area is red or feels warm', '🔥', 'severe', TRUE),
('symptom_lump_hard', 'medical_chest_breast_lump', 'الكتلة صلبة', 'Hard lump', 'الكتلة قاسية وغير متحركة', 'Lump is firm and doesn''t move', '🪨', 'severe', TRUE),
('symptom_lump_soft', 'medical_chest_breast_lump', 'الكتلة لينة', 'Soft lump', 'الكتلة طرية ومتحركة', 'Lump is soft and movable', '☁️', 'mild', FALSE),
('symptom_lump_size_change', 'medical_chest_breast_lump', 'الكتلة تكبر', 'Lump is growing', 'لاحظت أن حجم الكتلة يزداد', 'Noticed the lump is getting larger', '📈', 'severe', TRUE),
('symptom_lump_multiple', 'medical_chest_breast_lump', 'أكثر من كتلة', 'Multiple lumps', 'يوجد أكثر من كتلة واحدة', 'There is more than one lump', '🔴🔴', 'moderate', TRUE),
('symptom_lump_painful', 'medical_chest_breast_lump', 'الكتلة مؤلمة', 'Lump is painful', 'الكتلة تسبب ألم عند اللمس', 'Lump causes pain when touched', '😣', 'moderate', FALSE),
('symptom_lump_skin_change', 'medical_chest_breast_lump', 'تغير في الجلد فوق الكتلة', 'Skin changes over lump', 'الجلد فوق الكتلة متجعد أو متورم', 'Skin over lump is dimpled or swollen', '🍊', 'severe', TRUE),
('symptom_discharge_clear', 'medical_chest_nipple_discharge', 'إفرازات شفافة', 'Clear discharge', 'السائل شفاف أو أبيض', 'Fluid is clear or white', '💧', 'mild', FALSE),
('symptom_discharge_bloody', 'medical_chest_nipple_discharge', 'إفرازات دموية', 'Bloody discharge', 'السائل يحتوي على دم', 'Fluid contains blood', '🩸', 'severe', TRUE),
('symptom_discharge_spontaneous', 'medical_chest_nipple_discharge', 'إفرازات تلقائية', 'Spontaneous discharge', 'الإفرازات تخرج بدون عصر', 'Discharge happens without squeezing', '🚰', 'moderate', TRUE),
('symptom_discharge_both_nipples', 'medical_chest_nipple_discharge', 'من كلا الحلمتين', 'From both nipples', 'الإفرازات من الجهتين', 'Discharge from both sides', '↔️', 'mild', FALSE),
('symptom_discharge_one_nipple', 'medical_chest_nipple_discharge', 'من حلمة واحدة فقط', 'From one nipple only', 'الإفرازات من جهة واحدة', 'Discharge from one side only', '➡️', 'moderate', TRUE),
('symptom_bf_low_milk', 'medical_chest_breastfeeding', 'قلة إنتاج الحليب', 'Low milk supply', 'الطفل لا يشبع أو لا يزداد وزنه', 'Baby not satisfied or not gaining weight', '📉', 'moderate', FALSE),
('symptom_bf_painful', 'medical_chest_breastfeeding', 'ألم أثناء الرضاعة', 'Painful nursing', 'ألم شديد عند إرضاع الطفل', 'Severe pain when baby nurses', '😣', 'moderate', FALSE),
('symptom_bf_cracked_nipples', 'medical_chest_breastfeeding', 'تشقق الحلمات', 'Cracked nipples', 'الحلمات متشققة أو تنزف', 'Nipples are cracked or bleeding', '💔', 'moderate', FALSE),
('symptom_bf_engorgement', 'medical_chest_breastfeeding', 'احتقان الثدي', 'Breast engorgement', 'الثدي ممتلئ جداً وصلب', 'Breasts very full and hard', '🎈', 'moderate', FALSE),
('symptom_bf_mastitis', 'medical_chest_breastfeeding', 'التهاب الثدي', 'Mastitis', 'احمرار وحمى مع ألم في الثدي', 'Redness and fever with breast pain', '🔥', 'severe', TRUE),
('symptom_cardiac_pressure', 'medical_chest_cardiac', 'ضغط أو ثقل في الصدر', 'Chest pressure or heaviness', 'شعور بوزن ثقيل على الصدر', 'Feeling like heavy weight on chest', '🪨', 'severe', TRUE),
('symptom_cardiac_arm_pain', 'medical_chest_cardiac', 'ألم ينتشر للذراع', 'Pain radiating to arm', 'الألم ينتقل للكتف أو الذراع', 'Pain spreads to shoulder or arm', '💪', 'severe', TRUE),
('symptom_cardiac_shortness', 'medical_chest_cardiac', 'ضيق تنفس مع الألم', 'Shortness of breath with pain', 'صعوبة في التنفس مع ألم الصدر', 'Difficulty breathing with chest pain', '🫁', 'severe', TRUE),
('symptom_cardiac_sweating', 'medical_chest_cardiac', 'تعرق شديد', 'Severe sweating', 'تعرق غزير مع الألم', 'Heavy sweating with pain', '💦', 'severe', TRUE),
('symptom_cardiac_nausea', 'medical_chest_cardiac', 'غثيان أو دوخة', 'Nausea or dizziness', 'شعور بالغثيان أو دوار', 'Feeling nauseous or dizzy', '😵', 'severe', TRUE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO followup_questions (id, concern_id, question_ar, question_en, question_type, options, display_order, affects_urgency, affects_doctor_matching) VALUES
('fq_breast_pain_1', 'medical_chest_breast_pain', 'منذ متى وأنتِ تشعرين بهذا الألم؟', 'How long have you had this pain?', 'multiple_choice', '{"options": [{"value": "less_than_week", "label_ar": "أقل من أسبوع", "label_en": "Less than a week", "urgency_weight": 0}, {"value": "1_2_weeks", "label_ar": "أسبوع إلى أسبوعين", "label_en": "1-2 weeks", "urgency_weight": 1}, {"value": "2_4_weeks", "label_ar": "أسبوعين إلى شهر", "label_en": "2-4 weeks", "urgency_weight": 1}, {"value": "more_than_month", "label_ar": "أكثر من شهر", "label_en": "More than a month", "urgency_weight": 2}]}', 1, TRUE, FALSE),
('fq_breast_pain_2', 'medical_chest_breast_pain', 'هل سبق أن استشرتِ طبيبة بخصوص هذا الألم؟', 'Have you seen a doctor about this pain before?', 'yes_no', NULL, 2, FALSE, TRUE),
('fq_breast_pain_3', 'medical_chest_breast_pain', 'هل تناولتِ أي دواء للألم؟', 'Have you taken any medication for the pain?', 'yes_no', NULL, 3, FALSE, FALSE),
('fq_breast_lump_1', 'medical_chest_breast_lump', 'متى اكتشفتِ الكتلة؟', 'When did you discover the lump?', 'multiple_choice', '{"options": [{"value": "this_week", "label_ar": "هذا الأسبوع", "label_en": "This week", "urgency_weight": 3}, {"value": "last_week", "label_ar": "الأسبوع الماضي", "label_en": "Last week", "urgency_weight": 2}, {"value": "this_month", "label_ar": "هذا الشهر", "label_en": "This month", "urgency_weight": 2}, {"value": "more_than_month", "label_ar": "منذ أكثر من شهر", "label_en": "Over a month ago", "urgency_weight": 3}]}', 1, TRUE, FALSE),
('fq_breast_lump_2', 'medical_chest_breast_lump', 'هل يوجد تاريخ عائلي لسرطان الثدي؟', 'Is there a family history of breast cancer?', 'yes_no', NULL, 2, TRUE, TRUE),
('fq_breast_lump_3', 'medical_chest_breast_lump', 'هل أجريتِ فحص الماموجرام من قبل؟', 'Have you had a mammogram before?', 'yes_no', NULL, 3, FALSE, TRUE),
('fq_breastfeeding_1', 'medical_chest_breastfeeding', 'منذ متى ولدتِ؟', 'How long ago did you give birth?', 'multiple_choice', '{"options": [{"value": "less_than_week", "label_ar": "أقل من أسبوع", "label_en": "Less than a week"}, {"value": "1_4_weeks", "label_ar": "1-4 أسابيع", "label_en": "1-4 weeks"}, {"value": "1_3_months", "label_ar": "1-3 أشهر", "label_en": "1-3 months"}, {"value": "more_than_3_months", "label_ar": "أكثر من 3 أشهر", "label_en": "More than 3 months"}]}', 1, FALSE, TRUE),
('fq_breastfeeding_2', 'medical_chest_breastfeeding', 'هل هذا طفلك الأول؟', 'Is this your first baby?', 'yes_no', NULL, 2, FALSE, FALSE),
('fq_breastfeeding_3', 'medical_chest_breastfeeding', 'هل استشرتِ أخصائية رضاعة من قبل؟', 'Have you consulted a lactation specialist before?', 'yes_no', NULL, 3, FALSE, TRUE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO treatments (id, concern_id, name_ar, name_en, description_ar, description_en, type, average_cost_sar, duration_weeks, success_rate_percent) VALUES
('treatment_breast_pain_medication', 'medical_chest_breast_pain', 'مسكنات الألم', 'Pain medication', 'أدوية لتخفيف الألم وتقليل الالتهاب', 'Medications to relieve pain and reduce inflammation', 'medical', 150, 2, 85),
('treatment_breast_pain_hormone', 'medical_chest_breast_pain', 'علاج هرموني', 'Hormonal therapy', 'أدوية لتنظيم الهرمونات المسببة للألم', 'Medications to regulate hormones causing pain', 'medical', 500, 12, 75),
('treatment_lump_ultrasound', 'medical_chest_breast_lump', 'فحص بالموجات فوق الصوتية', 'Ultrasound examination', 'تصوير بالأشعة لتحديد طبيعة الكتلة', 'Imaging to determine nature of lump', 'medical', 400, 1, 95),
('treatment_lump_mammogram', 'medical_chest_breast_lump', 'فحص الماموجرام', 'Mammogram', 'أشعة متخصصة للكشف عن أي تغيرات', 'Specialized X-ray to detect changes', 'medical', 600, 1, 90),
('treatment_lump_biopsy', 'medical_chest_breast_lump', 'خزعة', 'Biopsy', 'أخذ عينة من الكتلة للفحص المخبري', 'Taking sample from lump for lab testing', 'surgical', 1500, 1, 99),
('treatment_bf_consultation', 'medical_chest_breastfeeding', 'استشارة أخصائية رضاعة', 'Lactation consultation', 'جلسة مع أخصائية لحل مشاكل الرضاعة', 'Session with specialist to solve nursing issues', 'therapy', 300, 1, 90),
('treatment_bf_medication', 'medical_chest_breastfeeding', 'أدوية لزيادة إنتاج الحليب', 'Milk-boosting medication', 'أدوية آمنة لزيادة إدرار الحليب', 'Safe medications to increase milk production', 'medical', 200, 4, 70)
ON CONFLICT (id) DO NOTHING;

-- MEDICAL ABDOMEN
INSERT INTO primary_concerns (id, body_part_id, name_ar, name_en, description_ar, description_en, icon, prevalence, urgency_default, requires_age_context, common_age_ranges, specialty_primary, specialty_secondary) VALUES
('medical_abdomen_pcos', 'medical_abdomen', 'تكيس المبايض', 'PCOS (Polycystic Ovary Syndrome)', 'اضطراب هرموني يؤثر على المبايض', 'Hormonal disorder affecting the ovaries', '🫐', 'very_common', 'moderate', TRUE, ARRAY['18-24', '25-34', '35-44'], 'Endocrinology', 'Gynecology'),
('medical_abdomen_irregular_periods', 'medical_abdomen', 'عدم انتظام الدورة الشهرية', 'Irregular Menstrual Periods', 'دورة شهرية غير منتظمة في الموعد أو الكمية', 'Menstrual cycle irregular in timing or flow', '📅', 'very_common', 'routine', TRUE, ARRAY['18-24', '25-34', '35-44'], 'Gynecology', 'Endocrinology'),
('medical_abdomen_period_pain', 'medical_abdomen', 'آلام الدورة الشهرية', 'Menstrual Cramps', 'ألم شديد أثناء الدورة الشهرية', 'Severe pain during menstrual period', '⚡', 'very_common', 'routine', TRUE, ARRAY['18-24', '25-34', '35-44'], 'Gynecology', NULL),
('medical_abdomen_endometriosis', 'medical_abdomen', 'الانتباذ البطاني الرحمي', 'Endometriosis', 'نمو نسيج الرحم خارج الرحم', 'Growth of uterine tissue outside the uterus', '🩸', 'common', 'moderate', TRUE, ARRAY['25-34', '35-44'], 'Gynecology', NULL),
('medical_abdomen_fertility', 'medical_abdomen', 'صعوبة الحمل', 'Fertility Issues', 'صعوبة في الحمل بعد محاولات منتظمة', 'Difficulty conceiving after regular attempts', '🤰', 'common', 'routine', TRUE, ARRAY['25-34', '35-44'], 'Fertility Specialist', 'Gynecology'),
('medical_abdomen_pregnancy', 'medical_abdomen', 'أعراض الحمل', 'Pregnancy Symptoms', 'أعراض محتملة للحمل أو مخاوف أثناء الحمل', 'Possible pregnancy symptoms or concerns during pregnancy', '👶', 'very_common', 'moderate', TRUE, ARRAY['18-24', '25-34', '35-44'], 'Obstetrics', NULL),
('medical_abdomen_ibs', 'medical_abdomen', 'القولون العصبي', 'Irritable Bowel Syndrome (IBS)', 'اضطراب في الجهاز الهضمي يسبب ألم وانتفاخ', 'Digestive disorder causing pain and bloating', '🌀', 'very_common', 'routine', FALSE, ARRAY['18-24', '25-34', '35-44', '45+'], 'Gastroenterology', NULL),
('medical_abdomen_bloating', 'medical_abdomen', 'الانتفاخ', 'Abdominal Bloating', 'انتفاخ وامتلاء في البطن', 'Swelling and fullness in abdomen', '🎈', 'very_common', 'routine', FALSE, ARRAY['18-24', '25-34', '35-44', '45+'], 'Gastroenterology', NULL),
('medical_abdomen_weight_gain', 'medical_abdomen', 'زيادة الوزن غير المبررة', 'Unexplained Weight Gain', 'زيادة في الوزن بدون سبب واضح', 'Weight increase without clear cause', '⬆️', 'common', 'routine', TRUE, ARRAY['25-34', '35-44', '45+'], 'Endocrinology', 'Nutrition'),
('medical_abdomen_pelvic_pain', 'medical_abdomen', 'ألم الحوض', 'Pelvic Pain', 'ألم في منطقة الحوض أسفل البطن', 'Pain in pelvic area below abdomen', '💥', 'common', 'moderate', TRUE, ARRAY['18-24', '25-34', '35-44'], 'Gynecology', NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO symptoms (id, concern_id, name_ar, name_en, description_ar, description_en, icon, severity_indicator, is_red_flag) VALUES
('symptom_pcos_irregular', 'medical_abdomen_pcos', 'دورة غير منتظمة', 'Irregular periods', 'الدورة تأتي كل 35+ يوم أو أقل من 8 مرات بالسنة', 'Period comes every 35+ days or less than 8 times/year', '📅', 'moderate', FALSE),
('symptom_pcos_no_period', 'medical_abdomen_pcos', 'انقطاع الدورة', 'Absent periods', 'لم تأتي الدورة منذ 3 أشهر أو أكثر', 'No period for 3 months or more', '⛔', 'moderate', TRUE),
('symptom_pcos_excess_hair', 'medical_abdomen_pcos', 'نمو شعر زائد', 'Excess hair growth', 'شعر في الوجه، الصدر، أو البطن', 'Hair on face, chest, or abdomen', '🧔', 'mild', FALSE),
('symptom_pcos_acne', 'medical_abdomen_pcos', 'حب الشباب', 'Acne', 'حب شباب شديد أو مستمر', 'Severe or persistent acne', '🔴', 'mild', FALSE),
('symptom_pcos_weight', 'medical_abdomen_pcos', 'صعوبة فقدان الوزن', 'Difficulty losing weight', 'زيادة وزن أو صعوبة في إنقاصه', 'Weight gain or difficulty losing it', '⚖️', 'mild', FALSE),
('symptom_pcos_hair_loss', 'medical_abdomen_pcos', 'تساقط شعر الرأس', 'Hair thinning', 'تساقط أو خفة شعر الرأس', 'Thinning or loss of scalp hair', '🍂', 'mild', FALSE),
('symptom_pcos_dark_patches', 'medical_abdomen_pcos', 'بقع داكنة على الجلد', 'Dark skin patches', 'بقع داكنة خلف الرقبة أو تحت الإبطين', 'Dark patches on neck or under arms', '🟤', 'mild', FALSE),
('symptom_pcos_skin_tags', 'medical_abdomen_pcos', 'زوائد جلدية', 'Skin tags', 'زوائد جلدية صغيرة في الرقبة أو الإبط', 'Small skin growths on neck or underarms', '🏷️', 'mild', FALSE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO followup_questions (id, concern_id, question_ar, question_en, question_type, options, display_order, affects_urgency, affects_doctor_matching) VALUES
('fq_pcos_1', 'medical_abdomen_pcos', 'منذ متى بدأتِ تلاحظين هذه الأعراض؟', 'How long have you been experiencing these symptoms?', 'multiple_choice', '{"options": [{"value": "less_than_6months", "label_ar": "أقل من 6 أشهر", "label_en": "Less than 6 months"}, {"value": "6months_1year", "label_ar": "6 أشهر إلى سنة", "label_en": "6 months to 1 year"}, {"value": "1_2years", "label_ar": "سنة إلى سنتين", "label_en": "1-2 years"}, {"value": "more_than_2years", "label_ar": "أكثر من سنتين", "label_en": "More than 2 years"}]}', 1, FALSE, FALSE),
('fq_pcos_2', 'medical_abdomen_pcos', 'هل تم تشخيصك بتكيس المبايض من قبل؟', 'Have you been diagnosed with PCOS before?', 'yes_no', NULL, 2, FALSE, TRUE),
('fq_pcos_3', 'medical_abdomen_pcos', 'هل تحاولين الحمل حالياً؟', 'Are you currently trying to conceive?', 'yes_no', NULL, 3, FALSE, TRUE),
('fq_pcos_4', 'medical_abdomen_pcos', 'هل لديك تاريخ عائلي لتكيس المبايض أو السكري؟', 'Do you have a family history of PCOS or diabetes?', 'yes_no', NULL, 4, FALSE, TRUE),
('fq_pcos_5', 'medical_abdomen_pcos', 'هل أجريتِ فحوصات الهرمونات من قبل؟', 'Have you had hormone tests before?', 'yes_no', NULL, 5, FALSE, TRUE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO treatments (id, concern_id, name_ar, name_en, description_ar, description_en, type, average_cost_sar, duration_weeks, success_rate_percent) VALUES
('treatment_pcos_lifestyle', 'medical_abdomen_pcos', 'تغيير نمط الحياة', 'Lifestyle modification', 'نظام غذائي وتمارين رياضية', 'Diet and exercise program', 'therapy', 500, 12, 70),
('treatment_pcos_metformin', 'medical_abdomen_pcos', 'ميتفورمين', 'Metformin', 'دواء لتنظيم السكر والهرمونات', 'Medication to regulate blood sugar and hormones', 'medical', 300, 12, 75),
('treatment_pcos_birth_control', 'medical_abdomen_pcos', 'حبوب منع الحمل', 'Birth control pills', 'لتنظيم الدورة والهرمونات', 'To regulate periods and hormones', 'medical', 200, 12, 80),
('treatment_pcos_fertility', 'medical_abdomen_pcos', 'أدوية الخصوبة', 'Fertility medications', 'لتحفيز التبويض إذا كنتِ تحاولين الحمل', 'To stimulate ovulation if trying to conceive', 'medical', 1500, 12, 65),
('treatment_pcos_laser_hair', 'medical_abdomen_pcos', 'إزالة الشعر بالليزر', 'Laser hair removal', 'لعلاج الشعر الزائد', 'To treat excess hair growth', 'cosmetic', 2000, 24, 85)
ON CONFLICT (id) DO NOTHING;
