-- File: supabase/seed/06_beauty_concerns.sql

-- BEAUTY FACE
INSERT INTO primary_concerns (id, body_part_id, name_ar, name_en, description_ar, description_en, icon, prevalence, urgency_default, requires_age_context, common_age_ranges, specialty_primary, specialty_secondary) VALUES
('beauty_face_wrinkles', 'beauty_face', 'التجاعيد وخطوط الوجه', 'Wrinkles & Fine Lines', 'خطوط وتجاعيد في الوجه', 'Lines and wrinkles on the face', '📏', 'very_common', 'routine', TRUE, ARRAY['35-44', '45+'], 'Dermatology', 'Plastic Surgery'),
('beauty_face_acne', 'beauty_face', 'حب الشباب وآثاره', 'Acne & Acne Scars', 'حبوب وآثار حب الشباب', 'Pimples and acne scars', '🔴', 'very_common', 'routine', TRUE, ARRAY['18-24', '25-34'], 'Dermatology', NULL),
('beauty_face_pigmentation', 'beauty_face', 'التصبغات والبقع الداكنة', 'Pigmentation & Dark Spots', 'بقع داكنة أو تصبغات في البشرة', 'Dark patches or skin discoloration', '☀️', 'very_common', 'routine', FALSE, ARRAY['25-34', '35-44', '45+'], 'Dermatology', NULL),
('beauty_face_contouring', 'beauty_face', 'نحت الوجه وتحديد الملامح', 'Facial Contouring', 'تحسين شكل وحجم ملامح الوجه', 'Enhancing face shape and features', '💎', 'common', 'routine', TRUE, ARRAY['25-34', '35-44', '45+'], 'Plastic Surgery', 'Dermatology'),
('beauty_face_lips', 'beauty_face', 'تكبير الشفاه', 'Lip Enhancement', 'زيادة حجم أو تحسين شكل الشفاه', 'Increasing size or improving lip shape', '👄', 'common', 'routine', TRUE, ARRAY['18-24', '25-34', '35-44'], 'Plastic Surgery', 'Dermatology'),
('beauty_face_nose', 'beauty_face', 'تجميل الأنف', 'Rhinoplasty', 'تغيير شكل أو حجم الأنف', 'Changing nose shape or size', '👃', 'common', 'routine', TRUE, ARRAY['18-24', '25-34', '35-44'], 'Plastic Surgery', NULL),
('beauty_face_texture', 'beauty_face', 'نعومة البشرة وإشراقتها', 'Skin Texture & Radiance', 'تحسين ملمس البشرة وإشراقتها', 'Improving skin smoothness and glow', '✨', 'very_common', 'routine', FALSE, ARRAY['18-24', '25-34', '35-44', '45+'], 'Dermatology', NULL),
('beauty_face_under_eye', 'beauty_face', 'الهالات والانتفاخ تحت العين', 'Dark Circles & Eye Bags', 'هالات سوداء أو انتفاخ تحت العين', 'Dark circles or puffiness under eyes', '👁️', 'very_common', 'routine', TRUE, ARRAY['25-34', '35-44', '45+'], 'Dermatology', 'Plastic Surgery')
ON CONFLICT (id) DO NOTHING;

INSERT INTO symptoms (id, concern_id, name_ar, name_en, description_ar, description_en, icon, severity_indicator) VALUES
('symptom_wrinkles_forehead', 'beauty_face_wrinkles', 'خطوط الجبين', 'Forehead lines', 'خطوط أفقية في الجبين', 'Horizontal lines on forehead', '➖', 'mild'),
('symptom_wrinkles_eyes', 'beauty_face_wrinkles', 'خطوط العين (أقدام الغراب)', 'Crow''s feet', 'خطوط حول العين عند الابتسام', 'Lines around eyes when smiling', '🦶', 'mild'),
('symptom_wrinkles_smile', 'beauty_face_wrinkles', 'خطوط الابتسامة', 'Smile lines', 'خطوط من الأنف للفم', 'Lines from nose to mouth', '😊', 'moderate'),
('symptom_wrinkles_lips', 'beauty_face_wrinkles', 'خطوط حول الفم', 'Lines around mouth', 'خطوط عمودية حول الشفاه', 'Vertical lines around lips', '👄', 'moderate'),
('symptom_wrinkles_neck', 'beauty_face_wrinkles', 'خطوط الرقبة', 'Neck lines', 'خطوط أفقية في الرقبة', 'Horizontal neck lines', '🦒', 'moderate'),
('symptom_wrinkles_deep', 'beauty_face_wrinkles', 'تجاعيد عميقة', 'Deep wrinkles', 'تجاعيد واضحة وعميقة', 'Obvious and deep wrinkles', '📏📏', 'severe')
ON CONFLICT (id) DO NOTHING;

INSERT INTO followup_questions (id, concern_id, question_ar, question_en, question_type, options, display_order, affects_urgency, affects_doctor_matching) VALUES
('fq_wrinkles_1', 'beauty_face_wrinkles', 'ما هي المنطقة التي تزعجك أكثر؟', 'Which area bothers you most?', 'multiple_choice', '{"options": [{"value": "forehead", "label_ar": "الجبين", "label_en": "Forehead"}, {"value": "eyes", "label_ar": "حول العين", "label_en": "Around eyes"}, {"value": "smile_lines", "label_ar": "خطوط الابتسامة", "label_en": "Smile lines"}, {"value": "lips", "label_ar": "حول الفم", "label_en": "Around mouth"}, {"value": "all", "label_ar": "كل المناطق", "label_en": "All areas"}]}', 1, FALSE, TRUE),
('fq_wrinkles_2', 'beauty_face_wrinkles', 'هل جربتِ أي علاج للتجاعيد من قبل؟', 'Have you tried any wrinkle treatments before?', 'multiple_choice', '{"options": [{"value": "none", "label_ar": "لا، لم أجرب", "label_en": "No, never tried"}, {"value": "creams", "label_ar": "كريمات فقط", "label_en": "Creams only"}, {"value": "botox", "label_ar": "بوتوكس", "label_en": "Botox"}, {"value": "fillers", "label_ar": "فيلر", "label_en": "Fillers"}, {"value": "laser", "label_ar": "ليزر", "label_en": "Laser"}]}', 2, FALSE, TRUE),
('fq_wrinkles_3', 'beauty_face_wrinkles', 'ما هي ميزانيتك التقريبية للعلاج؟', 'What is your approximate budget for treatment?', 'multiple_choice', '{"options": [{"value": "under_1000", "label_ar": "أقل من 1000 ريال", "label_en": "Under SAR 1,000"}, {"value": "1000_3000", "label_ar": "1000-3000 ريال", "label_en": "SAR 1,000-3,000"}, {"value": "3000_5000", "label_ar": "3000-5000 ريال", "label_en": "SAR 3,000-5,000"}, {"value": "above_5000", "label_ar": "أكثر من 5000 ريال", "label_en": "Above SAR 5,000"}, {"value": "not_sure", "label_ar": "غير متأكدة", "label_en": "Not sure"}]}', 3, FALSE, FALSE),
('fq_wrinkles_4', 'beauty_face_wrinkles', 'هل تفضلين علاجات سريعة أم طويلة الأمد؟', 'Do you prefer quick treatments or long-term solutions?', 'multiple_choice', '{"options": [{"value": "quick", "label_ar": "نتائج سريعة (حقن)", "label_en": "Quick results (injections)"}, {"value": "gradual", "label_ar": "نتائج تدريجية (كريمات/ليزر)", "label_en": "Gradual results (creams/laser)"}, {"value": "both", "label_ar": "كلاهما", "label_en": "Both"}, {"value": "not_sure", "label_ar": "غير متأكدة", "label_en": "Not sure"}]}', 4, FALSE, TRUE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO treatments (id, concern_id, name_ar, name_en, description_ar, description_en, type, average_cost_sar, duration_weeks, success_rate_percent) VALUES
('treatment_wrinkles_botox', 'beauty_face_wrinkles', 'بوتوكس', 'Botox', 'حقن للتقليل من حركة العضلات ومنع التجاعيد', 'Injections to reduce muscle movement and prevent wrinkles', 'cosmetic', 1500, 16, 95),
('treatment_wrinkles_fillers', 'beauty_face_wrinkles', 'فيلر', 'Dermal Fillers', 'حقن لملء التجاعيد واستعادة الحجم', 'Injections to fill wrinkles and restore volume', 'cosmetic', 2000, 24, 90),
('treatment_wrinkles_laser', 'beauty_face_wrinkles', 'ليزر فراكشنال', 'Fractional Laser', 'ليزر لتحفيز الكولاجين وتقليل التجاعيد', 'Laser to stimulate collagen and reduce wrinkles', 'cosmetic', 3000, 12, 80),
('treatment_wrinkles_peeling', 'beauty_face_wrinkles', 'التقشير الكيميائي', 'Chemical Peel', 'إزالة طبقات الجلد لتجديد البشرة', 'Removing skin layers to renew skin', 'cosmetic', 1200, 4, 75),
('treatment_wrinkles_microneedling', 'beauty_face_wrinkles', 'مايكرونيدلينج', 'Microneedling', 'وخز دقيق لتحفيز إنتاج الكولاجين', 'Tiny needles to stimulate collagen production', 'cosmetic', 1000, 8, 70),
('treatment_wrinkles_retinol', 'beauty_face_wrinkles', 'كريمات الريتينول', 'Retinol Creams', 'كريمات طبية لتحسين مظهر التجاعيد', 'Medical creams to improve wrinkle appearance', 'medical', 500, 24, 60)
ON CONFLICT (id) DO NOTHING;

-- BEAUTY ABDOMEN
INSERT INTO primary_concerns (id, body_part_id, name_ar, name_en, description_ar, description_en, icon, prevalence, urgency_default, requires_age_context, common_age_ranges, specialty_primary) VALUES
('beauty_abdomen_tummy_tuck', 'beauty_abdomen', 'شد البطن', 'Tummy Tuck (Abdominoplasty)', 'إزالة الجلد الزائد وشد عضلات البطن', 'Removing excess skin and tightening abdominal muscles', '📏', 'common', 'routine', TRUE, ARRAY['25-34', '35-44', '45+'], 'Plastic Surgery'),
('beauty_abdomen_liposuction', 'beauty_abdomen', 'شفط الدهون', 'Liposuction', 'إزالة الدهون الموضعية', 'Removing localized fat deposits', '💉', 'very_common', 'routine', FALSE, ARRAY['18-24', '25-34', '35-44', '45+'], 'Plastic Surgery'),
('beauty_abdomen_coolsculpting', 'beauty_abdomen', 'تجميد الدهون', 'CoolSculpting', 'تجميد الخلايا الدهنية بدون جراحة', 'Freezing fat cells non-surgically', '❄️', 'common', 'routine', FALSE, ARRAY['18-24', '25-34', '35-44', '45+'], 'Dermatology'),
('beauty_abdomen_stretch_marks', 'beauty_abdomen', 'علامات التمدد', 'Stretch Marks Treatment', 'علاج أو تقليل مظهر علامات التمدد', 'Treating or reducing appearance of stretch marks', '🌊', 'very_common', 'routine', TRUE, ARRAY['18-24', '25-34', '35-44'], 'Dermatology'),
('beauty_abdomen_csection_scar', 'beauty_abdomen', 'تحسين ندبة القيصرية', 'C-Section Scar Revision', 'تحسين مظهر ندبة الولادة القيصرية', 'Improving appearance of C-section scar', '🔲', 'common', 'routine', TRUE, ARRAY['25-34', '35-44'], 'Plastic Surgery'),
('beauty_abdomen_waist_sculpting', 'beauty_abdomen', 'نحت الخصر', 'Waist Sculpting', 'تحديد وتضييق منطقة الخصر', 'Defining and narrowing waist area', '⌛', 'common', 'routine', FALSE, ARRAY['18-24', '25-34', '35-44'], 'Plastic Surgery')
ON CONFLICT (id) DO NOTHING;

INSERT INTO symptoms (id, concern_id, name_ar, name_en, description_ar, description_en, icon) VALUES
('symptom_abdomen_loose_skin', 'beauty_abdomen_tummy_tuck', 'جلد مترهل', 'Loose/saggy skin', 'جلد زائد ومترهل في البطن', 'Excess, hanging skin on abdomen', '⬇️'),
('symptom_abdomen_separated_muscles', 'beauty_abdomen_tummy_tuck', 'انفصال عضلات البطن', 'Separated abdominal muscles', 'عضلات البطن منفصلة (غالباً بعد الحمل)', 'Abdominal muscles separated (often post-pregnancy)', '↔️'),
('symptom_abdomen_post_pregnancy', 'beauty_abdomen_tummy_tuck', 'تغيرات ما بعد الحمل', 'Post-pregnancy changes', 'البطن تغير بشكل كبير بعد الحمل', 'Abdomen changed significantly after pregnancy', '🤰'),
('symptom_abdomen_stubborn_fat', 'beauty_abdomen_liposuction', 'دهون عنيدة', 'Stubborn fat', 'دهون لا تذهب بالرياضة والحمية', 'Fat that doesn''t go away with diet and exercise', '🍔'),
('symptom_abdomen_love_handles', 'beauty_abdomen_liposuction', 'دهون الخصر الجانبية', 'Love handles', 'دهون على جانبي الخصر', 'Fat on sides of waist', '➡️⬅️'),
('symptom_abdomen_lower_belly', 'beauty_abdomen_liposuction', 'دهون أسفل البطن', 'Lower belly fat', 'تراكم دهون أسفل السرة', 'Fat accumulation below navel', '⬇️'),
('symptom_stretch_red', 'beauty_abdomen_stretch_marks', 'علامات تمدد حمراء', 'Red stretch marks', 'علامات حمراء أو أرجوانية حديثة', 'New red or purple stretch marks', '🔴'),
('symptom_stretch_white', 'beauty_abdomen_stretch_marks', 'علامات تمدد بيضاء', 'White stretch marks', 'علامات بيضاء أو فضية قديمة', 'Old white or silver stretch marks', '⚪'),
('symptom_stretch_deep', 'beauty_abdomen_stretch_marks', 'علامات عميقة', 'Deep stretch marks', 'علامات واضحة وعميقة', 'Obvious and deep stretch marks', '📏')
ON CONFLICT (id) DO NOTHING;

INSERT INTO followup_questions (id, concern_id, question_ar, question_en, question_type, options, display_order, affects_doctor_matching) VALUES
('fq_abdomen_beauty_1', 'beauty_abdomen_tummy_tuck', 'هل ولدتِ من قبل؟', 'Have you given birth before?', 'multiple_choice', '{"options": [{"value": "never", "label_ar": "لا، لم ألد", "label_en": "No, never"}, {"value": "once", "label_ar": "نعم، مرة واحدة", "label_en": "Yes, once"}, {"value": "twice", "label_ar": "نعم، مرتين", "label_en": "Yes, twice"}, {"value": "three_plus", "label_ar": "نعم، ثلاث مرات أو أكثر", "label_en": "Yes, three or more times"}]}', 1, TRUE),
('fq_abdomen_beauty_2', 'beauty_abdomen_tummy_tuck', 'هل تخططين للحمل مرة أخرى؟', 'Are you planning to get pregnant again?', 'multiple_choice', '{"options": [{"value": "no_sure", "label_ar": "لا، أنا متأكدة", "label_en": "No, I''m sure"}, {"value": "not_planning", "label_ar": "لا أخطط حالياً", "label_en": "Not planning currently"}, {"value": "maybe", "label_ar": "ربما في المستقبل", "label_en": "Maybe in the future"}, {"value": "yes", "label_ar": "نعم، قريباً", "label_en": "Yes, soon"}]}', 2, TRUE),
('fq_abdomen_beauty_3', 'beauty_abdomen_liposuction', 'ما هو مؤشر كتلة جسمك (BMI) التقريبي؟', 'What is your approximate BMI?', 'multiple_choice', '{"options": [{"value": "normal", "label_ar": "طبيعي (18-25)", "label_en": "Normal (18-25)"}, {"value": "slightly_over", "label_ar": "زيادة بسيطة (25-30)", "label_en": "Slightly overweight (25-30)"}, {"value": "overweight", "label_ar": "زيادة (30-35)", "label_en": "Overweight (30-35)"}, {"value": "not_sure", "label_ar": "غير متأكدة", "label_en": "Not sure"}]}', 1, TRUE),
('fq_abdomen_beauty_4', 'beauty_abdomen_liposuction', 'هل تمارسين الرياضة بانتظام؟', 'Do you exercise regularly?', 'multiple_choice', '{"options": [{"value": "regular", "label_ar": "نعم، بانتظام", "label_en": "Yes, regularly"}, {"value": "sometimes", "label_ar": "أحياناً", "label_en": "Sometimes"}, {"value": "rarely", "label_ar": "نادراً", "label_en": "Rarely"}, {"value": "never", "label_ar": "لا", "label_en": "No"}]}', 2, FALSE),
('fq_abdomen_beauty_5', 'beauty_abdomen_stretch_marks', 'متى ظهرت علامات التمدد؟', 'When did the stretch marks appear?', 'multiple_choice', '{"options": [{"value": "recent", "label_ar": "خلال 6 أشهر الماضية", "label_en": "Within last 6 months"}, {"value": "1year", "label_ar": "منذ سنة", "label_en": "About a year ago"}, {"value": "2plus_years", "label_ar": "منذ سنتين أو أكثر", "label_en": "2+ years ago"}, {"value": "very_old", "label_ar": "منذ سنوات عديدة", "label_en": "Many years ago"}]}', 1, FALSE)
ON CONFLICT (id) DO NOTHING;
