-- File: supabase/seed/07_mental_concerns.sql

-- MENTAL BRAIN/MIND
INSERT INTO primary_concerns (id, body_part_id, name_ar, name_en, description_ar, description_en, icon, prevalence, urgency_default, requires_age_context, common_age_ranges, specialty_primary) VALUES
('mental_brain_anxiety', 'mental_brain', 'القلق والتوتر', 'Anxiety & Stress', 'شعور مستمر بالقلق والتوتر', 'Persistent feelings of worry and tension', '😰', 'very_common', 'moderate', FALSE, ARRAY['18-24', '25-34', '35-44', '45+'], 'Psychiatry'),
('mental_brain_depression', 'mental_brain', 'الاكتئاب', 'Depression', 'حزن مستمر وفقدان الاهتمام بالأنشطة', 'Persistent sadness and loss of interest', '😔', 'very_common', 'moderate', FALSE, ARRAY['18-24', '25-34', '35-44', '45+'], 'Psychiatry'),
('mental_brain_insomnia', 'mental_brain', 'الأرق وصعوبة النوم', 'Insomnia & Sleep Issues', 'صعوبة في النوم أو البقاء نائماً', 'Difficulty falling or staying asleep', '😴', 'very_common', 'routine', FALSE, ARRAY['18-24', '25-34', '35-44', '45+'], 'Psychiatry'),
('mental_brain_postpartum', 'mental_brain', 'اكتئاب ما بعد الولادة', 'Postpartum Depression', 'حزن وقلق شديد بعد الولادة', 'Severe sadness and anxiety after childbirth', '👶💔', 'common', 'urgent', TRUE, ARRAY['18-24', '25-34', '35-44'], 'Psychiatry'),
('mental_brain_trauma', 'mental_brain', 'صدمات نفسية', 'Trauma & PTSD', 'ذكريات وأعراض بعد حدث صادم', 'Memories and symptoms after traumatic event', '💔', 'common', 'moderate', FALSE, ARRAY['18-24', '25-34', '35-44', '45+'], 'Psychiatry'),
('mental_brain_ocd', 'mental_brain', 'الوسواس القهري', 'OCD', 'أفكار متكررة وسلوكيات قهرية', 'Repetitive thoughts and compulsive behaviors', '🔄', 'common', 'moderate', FALSE, ARRAY['18-24', '25-34', '35-44'], 'Psychiatry'),
('mental_brain_panic', 'mental_brain', 'نوبات الهلع', 'Panic Attacks', 'نوبات مفاجئة من الخوف الشديد', 'Sudden episodes of intense fear', '😱', 'common', 'moderate', FALSE, ARRAY['18-24', '25-34', '35-44'], 'Psychiatry'),
('mental_brain_adhd', 'mental_brain', 'صعوبة التركيز', 'Focus & ADHD', 'صعوبة في التركيز والانتباه', 'Difficulty concentrating and paying attention', '🧩', 'common', 'routine', TRUE, ARRAY['18-24', '25-34'], 'Psychiatry')
ON CONFLICT (id) DO NOTHING;

INSERT INTO symptoms (id, concern_id, name_ar, name_en, description_ar, description_en, icon, severity_indicator, is_red_flag) VALUES
('symptom_anxiety_worry', 'mental_brain_anxiety', 'قلق مستمر', 'Constant worrying', 'أفكار قلق لا تتوقف', 'Worry thoughts that won''t stop', '🌀', 'moderate', FALSE),
('symptom_anxiety_restless', 'mental_brain_anxiety', 'شعور بعدم الراحة', 'Feeling restless', 'عدم القدرة على الاسترخاء', 'Unable to relax', '😣', 'mild', FALSE),
('symptom_anxiety_tired', 'mental_brain_anxiety', 'تعب دائم', 'Constant fatigue', 'تعب رغم عدم بذل مجهود', 'Tired despite no exertion', '😴', 'moderate', FALSE),
('symptom_anxiety_heart', 'mental_brain_anxiety', 'خفقان القلب', 'Heart racing', 'ضربات قلب سريعة', 'Fast heartbeat', '💓', 'moderate', TRUE),
('symptom_anxiety_breathe', 'mental_brain_anxiety', 'صعوبة في التنفس', 'Difficulty breathing', 'شعور بضيق التنفس', 'Feeling like can''t breathe', '🫁', 'severe', TRUE),
('symptom_anxiety_sweating', 'mental_brain_anxiety', 'تعرق زائد', 'Excessive sweating', 'تعرق بدون سبب', 'Sweating without reason', '💦', 'mild', FALSE),
('symptom_anxiety_stomach', 'mental_brain_anxiety', 'مشاكل في المعدة', 'Stomach problems', 'غثيان أو آلام معدة', 'Nausea or stomach aches', '🤢', 'moderate', FALSE),
('symptom_anxiety_sleep', 'mental_brain_anxiety', 'صعوبة النوم', 'Sleep difficulty', 'الأفكار تمنعك من النوم', 'Thoughts keep you awake', '😴', 'moderate', FALSE),
('symptom_depression_sad', 'mental_brain_depression', 'حزن مستمر', 'Persistent sadness', 'حزن لا يذهب', 'Sadness that won''t go away', '😢', 'severe', TRUE),
('symptom_depression_no_interest', 'mental_brain_depression', 'فقدان الاهتمام', 'Loss of interest', 'لا تستمتعين بما كنتِ تحبين', 'Don''t enjoy things you used to love', '😐', 'severe', TRUE),
('symptom_depression_hopeless', 'mental_brain_depression', 'شعور باليأس', 'Feeling hopeless', 'شعور أن لا شيء سيتحسن', 'Feeling nothing will improve', '💔', 'severe', TRUE),
('symptom_depression_tired', 'mental_brain_depression', 'تعب شديد', 'Severe fatigue', 'لا طاقة للقيام بأي شيء', 'No energy to do anything', '😴', 'moderate', FALSE),
('symptom_depression_appetite', 'mental_brain_depression', 'تغير في الشهية', 'Appetite changes', 'أكل أكثر أو أقل من المعتاد', 'Eating more or less than usual', '🍽️', 'moderate', FALSE),
('symptom_depression_sleep', 'mental_brain_depression', 'اضطرابات النوم', 'Sleep disturbances', 'نوم كثير جداً أو قليل جداً', 'Sleeping too much or too little', '😴', 'moderate', FALSE),
('symptom_depression_worthless', 'mental_brain_depression', 'شعور بانعدام القيمة', 'Feeling worthless', 'شعور أنك لا قيمة لك', 'Feeling you have no value', '😞', 'severe', TRUE),
('symptom_depression_suicidal', 'mental_brain_depression', 'أفكار انتحارية', 'Suicidal thoughts', 'أفكار عن إيذاء النفس', 'Thoughts about self-harm', '🚨', 'severe', TRUE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO followup_questions (id, concern_id, question_ar, question_en, question_type, options, display_order, affects_urgency, affects_doctor_matching) VALUES
('fq_anxiety_1', 'mental_brain_anxiety', 'منذ متى وأنتِ تشعرين بهذا القلق؟', 'How long have you felt this anxiety?', 'multiple_choice', '{"options": [{"value": "days", "label_ar": "بضعة أيام", "label_en": "A few days"}, {"value": "weeks", "label_ar": "بضعة أسابيع", "label_en": "A few weeks"}, {"value": "months", "label_ar": "عدة أشهر", "label_en": "Several months"}, {"value": "years", "label_ar": "سنوات", "label_en": "Years"}]}', 1, TRUE, FALSE),
('fq_anxiety_2', 'mental_brain_anxiety', 'هل يؤثر القلق على حياتك اليومية؟', 'Does anxiety affect your daily life?', 'multiple_choice', '{"options": [{"value": "not_much", "label_ar": "لا، ليس كثيراً", "label_en": "No, not much"}, {"value": "sometimes", "label_ar": "أحياناً", "label_en": "Sometimes"}, {"value": "often", "label_ar": "غالباً", "label_en": "Often"}, {"value": "always", "label_ar": "دائماً، يؤثر بشدة", "label_en": "Always, severely affects"}]}', 2, TRUE, FALSE),
('fq_anxiety_3', 'mental_brain_anxiety', 'هل جربتِ العلاج النفسي أو الدواء من قبل؟', 'Have you tried therapy or medication before?', 'multiple_choice', '{"options": [{"value": "never", "label_ar": "لا، أبداً", "label_en": "No, never"}, {"value": "therapy_only", "label_ar": "علاج نفسي فقط", "label_en": "Therapy only"}, {"value": "medication_only", "label_ar": "دواء فقط", "label_en": "Medication only"}, {"value": "both", "label_ar": "كلاهما", "label_en": "Both"}]}', 3, FALSE, TRUE),
('fq_depression_1', 'mental_brain_depression', 'هل لديك أفكار عن إيذاء نفسك؟', 'Do you have thoughts about harming yourself?', 'yes_no', NULL, 1, TRUE, TRUE),
('fq_depression_2', 'mental_brain_depression', 'هل تستطيعين الاعتناء بنفسك يومياً؟', 'Can you take care of yourself daily?', 'multiple_choice', '{"options": [{"value": "yes_normally", "label_ar": "نعم، بشكل طبيعي", "label_en": "Yes, normally"}, {"value": "with_effort", "label_ar": "نعم، بجهد", "label_en": "Yes, with effort"}, {"value": "barely", "label_ar": "بالكاد", "label_en": "Barely"}, {"value": "no", "label_ar": "لا أستطيع", "label_en": "No, I can''t"}]}', 2, TRUE, TRUE),
('fq_depression_3', 'mental_brain_depression', 'هل لديك دعم من العائلة أو الأصدقاء؟', 'Do you have support from family or friends?', 'multiple_choice', '{"options": [{"value": "strong", "label_ar": "نعم، دعم قوي", "label_en": "Yes, strong support"}, {"value": "some", "label_ar": "بعض الدعم", "label_en": "Some support"}, {"value": "little", "label_ar": "دعم قليل", "label_en": "Little support"}, {"value": "none", "label_ar": "لا يوجد دعم", "label_en": "No support"}]}', 3, TRUE, FALSE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO treatments (id, concern_id, name_ar, name_en, description_ar, description_en, type, average_cost_sar, duration_weeks, success_rate_percent) VALUES
('treatment_anxiety_therapy', 'mental_brain_anxiety', 'العلاج المعرفي السلوكي', 'Cognitive Behavioral Therapy (CBT)', 'جلسات علاج نفسي لتغيير أنماط التفكير', 'Therapy sessions to change thought patterns', 'therapy', 400, 12, 80),
('treatment_anxiety_medication', 'mental_brain_anxiety', 'أدوية مضادة للقلق', 'Anti-anxiety medication', 'أدوية للتحكم في أعراض القلق', 'Medications to control anxiety symptoms', 'medical', 300, 12, 75),
('treatment_anxiety_relaxation', 'mental_brain_anxiety', 'تقنيات الاسترخاء', 'Relaxation techniques', 'تمارين تنفس وتأمل', 'Breathing exercises and meditation', 'therapy', 200, 8, 70),
('treatment_depression_therapy', 'mental_brain_depression', 'العلاج النفسي', 'Psychotherapy', 'جلسات علاج نفسي متخصصة', 'Specialized therapy sessions', 'therapy', 400, 16, 75),
('treatment_depression_medication', 'mental_brain_depression', 'مضادات الاكتئاب', 'Antidepressant medication', 'أدوية لتحسين المزاج', 'Medications to improve mood', 'medical', 350, 24, 70),
('treatment_depression_combined', 'mental_brain_depression', 'علاج مشترك (دواء + علاج نفسي)', 'Combined treatment', 'الجمع بين الدواء والعلاج النفسي', 'Combining medication and therapy', 'medical', 750, 24, 85)
ON CONFLICT (id) DO NOTHING;
