const fs = require('fs');

const conditions = [
    {
        name_en: "PCOS",
        name_ar: "متلازمة تكيس المبايض",
        slug: "pcos",
        specialty: "OB/GYN",
        overview: "حالة هرمونية شائعة تؤثر على النساء في سن الإنجاب. تسبب عدم انتظام الدورة الشهرية وزيادة نمو الشعر.",
        symptoms: "عدم انتظام الدورة الشهرية، زيادة الوزن، حب الشباب، نمو الشعر الزائد.",
        causes: "زيادة الأندروجين، مقاومة الأنسولين، عوامل وراثية.",
        diagnosis: "فحص الحوض، الموجات فوق الصوتية، تحاليل الدم.",
        treatment: "تصحيح نمط الحياة، أدوية تنظيم الدورة، علاج الخصوبة."
    },
    {
        name_en: "Endometriosis",
        name_ar: "بطانة الرحم المهاجرة",
        slug: "endometriosis",
        specialty: "OB/GYN",
        overview: "حالة ينمو فيها نسيج مشابه لبطانة الرحم خارج الرحم، مما يسبب ألماً شديداً ومشاكل في الخصوبة.",
        symptoms: "ألم الحوض المزمن، ألم شديد أثناء الدورة، ألم أثناء الجماع.",
        causes: "غير معروفة بدقة، قد تشمل الحيض الرجعي والعوامل الوراثية.",
        diagnosis: "تنظير البطن، الفحص السريري، الرنين المغناطيسي.",
        treatment: "مسكنات الألم، العلاج الهرموني، الجراحة."
    },
    {
        name_en: "Gestational Diabetes",
        name_ar: "سكري الحمل",
        slug: "gestational-diabetes",
        specialty: "OB/GYN",
        overview: "ارتفاع سكر الدم الذي يتطور أثناء الحمل ويختفي عادة بعد الولادة.",
        symptoms: "زيادة العطش، التبول المتكرر، التعب.",
        causes: "التغيرات الهرمونية أثناء الحمل التي تؤثر على عمل الأنسولين.",
        diagnosis: "اختبار تحمل الجلوكوز الفموي.",
        treatment: "مراقبة سكر الدم، نظام غذائي صحي، الأنسولين إذا لزم الأمر."
    },
    {
        name_en: "Postpartum Depression",
        name_ar: "اكتئاب ما بعد الولادة",
        slug: "postpartum-depression",
        specialty: "Mental Health",
        overview: "نوع من الاكتئاب يحدث بعد الولادة، يتجاوز كآبة النفاس العادية ويؤثر على القدرة على العناية بالطفل.",
        symptoms: "تقلبات مزاجية حادة، انسحاب من العائلة، صعوبة في الارتباط بالطفل.",
        causes: "انخفاض حاد في الهرمونات بعد الولادة، الحرمان من النوم، الضغوط النفسية.",
        diagnosis: "تقييم نفسي شامل.",
        treatment: "العلاج النفسي، مضادات الاكتئاب."
    },
    {
        name_en: "UTI",
        name_ar: "التهاب المسالك البولية",
        slug: "uti",
        specialty: "General Practice",
        overview: "عدوى تصيب أي جزء من الجهاز البولي، وهي أكثر شيوعاً لدى النساء.",
        symptoms: "حرقان أثناء التبول، حاجة ملحة للتبول، ألم في الحوض.",
        causes: "بكتيريا تدخل مجرى البول.",
        diagnosis: "تحليل البول.",
        treatment: "المضادات الحيوية، شرب الكثير من السوائل."
    },
    {
        name_en: "Breast Cancer",
        name_ar: "سرطان الثدي",
        slug: "breast-cancer",
        specialty: "General Practice",
        overview: "سرطان يتشكل في خلايا الثدي. الكشف المبكر يزيد بشكل كبير من فرص الشفاء.",
        symptoms: "كتلة في الثدي، تغير في شكل الثدي، إفرازات غير طبيعية.",
        causes: "طفرات جينية (BRCA)، التقدم في العمر، التاريخ العائلي.",
        diagnosis: "الماموجرام، الموجات فوق الصوتية، الخزعة.",
        treatment: "الجراحة، العلاج الكيماوي، العلاج الإشعاعي."
    },
    {
        name_en: "Menopause",
        name_ar: "انقطاع الطمث",
        slug: "menopause",
        specialty: "OB/GYN",
        overview: "نهاية الدورة الشهرية بشكل طبيعي، عادة في سن 45-55.",
        symptoms: "هبات ساخنة، تعرق ليلي، تقلبات مزاجية، جفاف مهبلي.",
        causes: "انخفاض طبيعي في الهرمونات التناسلية.",
        diagnosis: "فحص الدم لمستويات الهرمونات (FSH).",
        treatment: "العلاج الهرموني التعويضي، تغييرات نمط الحياة."
    },
    {
        name_en: "Fibroids",
        name_ar: "الألياف الرحمية",
        slug: "fibroids",
        specialty: "OB/GYN",
        overview: "أورام غير سرطانية في الرحم تظهر غالباً خلال سنوات الإنجاب.",
        symptoms: "نزيض حيض غزير، ألم في الحوض، تكرار التبول.",
        causes: "تغيرات جينية، هرمونات (استروجين وبروجسترون).",
        diagnosis: "الموجات فوق الصوتية، الرنين المغناطيسي.",
        treatment: "الأدوية، الجراحة (استئصال الورم أو الرحم)."
    }
];

let sql = `-- Seed Encyclopedia Content
-- Generated by script

-- Clear existing data if you want fresh start
-- TRUNCATE TABLE medical_conditions CASCADE;

`;

conditions.forEach((cond) => {
    // Append causes to overview since causes column doesn't exist in schema
    const overviewCombined = `${cond.overview}\n\nالأسباب:\n${cond.causes}`;

    sql += `
DO $$
DECLARE
    new_id UUID := uuid_generate_v4();
BEGIN
    INSERT INTO medical_conditions (
        id, 
        name_en, 
        name_ar, 
        slug, 
        overview_ar, 
        symptoms_ar, 
        diagnosis_ar, 
        treatment_ar, 
        specialty,
        created_at
    )
    VALUES (
        new_id,
        '${cond.name_en}',
        '${cond.name_ar}',
        '${cond.slug}',
        '${overviewCombined}',
        '${cond.symptoms}',
        '${cond.diagnosis}',
        '${cond.treatment}',
        '${cond.specialty}',
        now()
    );
EXCEPTION WHEN unique_violation THEN NULL;
END $$;
`;
});

fs.writeFileSync('supabase/migrations/20241206_seed_encyclopedia_full.sql', sql);
console.log('Successfully generated Encyclopedia seed file.');
