const fs = require('fs');
const crypto = require('crypto');

function uuidv4() {
    return "10000000-1000-4000-8000-100000000000".replace(/[018]/g, c =>
        (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
    );
}

const firstNamesAr = ['نورا', 'سارة', 'ريم', 'أمل', 'هياء', 'مها', 'لطيفة', 'منيرة', 'حصة', 'الجوهرة', 'دلال', 'سمر', 'فاطمة', 'عائشة', 'ليلى', 'خلود', 'أسماء', 'بشاير', 'تهاني', 'جميلة'];
const firstNamesEn = ['Noura', 'Sara', 'Reem', 'Amal', 'Haya', 'Maha', 'Latifa', 'Munira', 'Hessa', 'Aljawhara', 'Dalal', 'Samar', 'Fatima', 'Aisha', 'Layla', 'Kholoud', 'Asma', 'Bashayer', 'Tahani', 'Jamila'];

const lastNamesAr = ['الراشد', 'القحطاني', 'العتيبي', 'الحربي', 'الزهراني', 'العمري', 'الغامدي', 'الدوسري', 'المطيري', 'الشهري', 'العنزي', 'السبيعي', 'الشمراني', 'المالكي', 'السالم', 'الفهد', 'السليمان', 'الخالد', 'العلي', 'الحمد'];
const lastNamesEn = ['Al-Rashid', 'Al-Qahtani', 'Al-Otaibi', 'Al-Harbi', 'Al-Zahrani', 'Al-Omari', 'Al-Ghamdi', 'Al-Dossari', 'Al-Mutairi', 'Al-Shehri', 'Al-Enezi', 'Al-Subaie', 'Al-Shamrani', 'Al-Maliki', 'Al-Salem', 'Al-Fahad', 'Al-Sulaiman', 'Al-Khalid', 'Al-Ali', 'Al-Hamad'];

const specialties = [
    {
        code: 'OB/GYN',
        sub: ['Infertility & IVF', 'Pregnancy Follow-up', 'Fetal Medicine'],
        hospitals: ['King Faisal Specialist Hospital', 'Dallah Hospital', 'Habib Medical Group'],
        bioAr: 'استشارية أمراض النساء والولادة وعلاج العقم. خبرة واسعة في متابعة الحمل عالي الخطورة وعمليات أطفال الأنابيب.',
        bioEn: 'Consultant OB/GYN and Infertility specialist. Extensive experience in high-risk pregnancies and IVF procedures.'
    },
    {
        code: 'OB/GYN',
        sub: ['Cosmetic Gynecology', 'Laser Therapy'],
        hospitals: ['Derma Clinic', 'Kaya Skin Clinic', 'Habib Medical Group'],
        bioAr: 'استشارية النساء والولادة والتجميل النسائي. متخصصة في الإجراءات التجميلية والعلاجية بالليزر.',
        bioEn: 'Consultant OB/GYN specializing in cosmetic gynecology and laser therapies.'
    },
    {
        code: 'Dermatology',
        sub: ['Cosmetic Dermatology', 'Laser', 'Anti-Aging'],
        hospitals: ['Derma Clinic', 'Kaya Skin Clinic', 'Habib Medical Group'],
        bioAr: 'استشارية جلدية وتجميل والليزر. متخصصة في الحقن التجميلي والعناية بالبشرة.',
        bioEn: 'Consultant Dermatologist and Cosmetic Laser specialist. Expert in aesthetic injections and skin care.'
    },
    {
        code: 'Mental Health',
        sub: ['Women\'s Psychiatry', 'Postpartum Depression', 'Anxiety'],
        hospitals: ['Maudsley Health', 'Mutmaena Center', 'Medcare Hospital'],
        bioAr: 'استشارية الطب النفسي، متخصصة في صحة المرأة النفسية، واكتئاب ما بعد الولادة والقلق.',
        bioEn: 'Consultant Psychiatrist specializing in women\'s mental health, postpartum depression, and anxiety.'
    },
    {
        code: 'Nutrition',
        sub: ['Weight Management', 'Pregnancy Nutrition', 'PCOS Diet'],
        hospitals: ['Diet Center', 'Wellness Clinic', 'Habib Medical Group'],
        bioAr: 'أخصائية تغذية علاجية، برامج متخصصة لمرضى تكيس المبايض وتغذية الحوامل وإنقاص الوزن.',
        bioEn: 'Clinical Nutritionist specializing in PCOS management, pregnancy nutrition, and weight loss.'
    },
    {
        code: 'Breast Surgery',
        sub: ['Breast Oncology', 'Reconstructive Surgery'],
        hospitals: ['King Faisal Specialist Hospital', 'King Fahad Medical City'],
        bioAr: 'استشارية جراحة أورام الثدي والجراحة الترميمية. الكشف المبكر والعلاج الجراحي.',
        bioEn: 'Consultant Breast Surgeon specializing in oncology and reconstructive surgery.'
    },
    {
        code: 'Family Medicine',
        sub: ['Women\'s Health', 'Preventive Care'],
        hospitals: ['My Clinic', 'Family Care Center'],
        bioAr: 'طبيبة أسرة متخصصة في صحة المرأة والفحوصات الوقائية الشاملة.',
        bioEn: 'Family Medicine Consultant focusing on women\'s health and comprehensive preventive care.'
    }
];

const cities = ['Riyadh', 'Jeddah', 'Dammam', 'Khobar', 'Mecca', 'Medina'];

const images = [
    '/images/doctors/doctor_noura_alrashid_1764849899936.png',
    '/images/doctors/doctor_sarah_ahmed_1764849887752.png',
    '/images/doctors/doctor_leila_khalid_1764849830840.png',
    '/images/doctors/doctor_fatima_ali_1764849767672.png',
    '/images/doctors/doctor_amira_fahad_1764849818816.png',
    '/images/doctors/ai_doctor_grey.png',
    '/images/doctors/ai_doctor_blue.png',
    '/images/doctors/ai_doctor_senior.png',
    '/images/doctors/ai_doctor_beige.png'
];

let sql = `-- Seed 100 Doctors Data (Women's Health MVP)
-- Generated by script

-- CLEANUP EXISTING DATA
TRUNCATE TABLE doctors CASCADE;
-- TRUNCATE TABLE profiles CASCADE; -- Be careful, this wipes admin too if not handled. Better to just wipe doctors via cascade.

`;

// Generate 100 entries
for (let i = 0; i < 100; i++) {
    constfirstNameIndex = Math.floor(Math.random() * firstNamesAr.length);
    const lastNameIndex = Math.floor(Math.random() * lastNamesAr.length);

    const firstNameAr = firstNamesAr[Math.floor(Math.random() * firstNamesAr.length)];
    const firstNameEn = firstNamesEn[Math.floor(Math.random() * firstNamesEn.length)];
    const lastNameAr = lastNamesAr[lastNameIndex];
    const lastNameEn = lastNamesEn[lastNameIndex];

    const fullNameAr = `د. ${firstNameAr} ${lastNameAr}`;
    const fullNameEn = `Dr. ${firstNameEn} ${lastNameEn}`;

    const spec = specialties[Math.floor(Math.random() * specialties.length)];
    const escapedSubSpecialties = spec.sub.map(s => s.replace(/'/g, "''"));
    const escapedBioAr = spec.bioAr.replace(/'/g, "''");
    const escapedBioEn = spec.bioEn.replace(/'/g, "''");
    const city = cities[Math.floor(Math.random() * cities.length)];
    const hospital = spec.hospitals[Math.floor(Math.random() * spec.hospitals.length)];
    const image = images[i % images.length];

    // UUIDs
    const userId = uuidv4();
    const doctorId = uuidv4();

    // Random data
    const expYears = Math.floor(Math.random() * 25) + 5; // 5 to 30
    const price = (Math.floor(Math.random() * 8) + 3) * 50; // 150 to 500
    const rating = (Math.random() * (5.0 - 4.2) + 4.2).toFixed(1); // 4.2 to 5.0
    const totalConsultations = Math.floor(Math.random() * 500) + 50;

    const email = `${firstNameEn.toLowerCase()}.${lastNameEn.toLowerCase()}.${i + 100}@marham.sa`;


    sql += `
-- Doctor ${i + 1}: ${fullNameEn}
DO $$
BEGIN
    -- Cleanup existing user with this email to prevent ID mismatch
    DELETE FROM auth.users WHERE email = '${email}';
    
    INSERT INTO auth.users (
        id, instance_id, email, encrypted_password, email_confirmed_at, 
        created_at, updated_at, raw_app_meta_data, raw_user_meta_data, aud, role
    ) VALUES (
        '${userId}', '00000000-0000-0000-0000-000000000000', '${email}', 
        crypt('password123', gen_salt('bf')), now(), now(), now(), 
        '{"provider":"email","providers":["email"]}', 
        '{"full_name":"${fullNameEn}","role":"doctor"}', 
        'authenticated', 'authenticated'
    );
EXCEPTION WHEN unique_violation THEN NULL;
END $$;

DO $$
BEGIN
    INSERT INTO profiles (id, role, full_name_ar, full_name_en, city, created_at, updated_at)
    VALUES (
        '${userId}', 'doctor', '${fullNameAr}', '${fullNameEn}', '${city}', now(), now()
    );
EXCEPTION WHEN unique_violation THEN NULL;
END $$;

DO $$
BEGIN
    INSERT INTO doctors (
        id, profile_id, scfhs_license, specialty, sub_specialties, hospital, 
        experience_years, consultation_price, rating, total_consultations, 
        status, profile_photo_url, bio_ar, bio_en, created_at, updated_at
    ) VALUES (
        '${doctorId}', '${userId}', '${100000 + i}', '${spec.code}', 
        ARRAY['${escapedSubSpecialties.join("','")}'], '${hospital}', 
        ${expYears}, ${price}, ${rating}, ${totalConsultations}, 
        'approved', '${image}', '${escapedBioAr}', '${escapedBioEn}', now(), now()
    );
EXCEPTION WHEN unique_violation THEN NULL;
END $$;

INSERT INTO doctor_schedules (id, doctor_id, day_of_week, start_time, end_time, is_available)
VALUES
    (uuid_generate_v4(), '${doctorId}', 1, '09:00', '17:00', true),
    (uuid_generate_v4(), '${doctorId}', 2, '09:00', '17:00', true),
    (uuid_generate_v4(), '${doctorId}', 3, '09:00', '14:00', true),
    (uuid_generate_v4(), '${doctorId}', 4, '13:00', '21:00', true),
    (uuid_generate_v4(), '${doctorId}', 0, '10:00', '16:00', true);
`;
}

fs.writeFileSync('supabase/migrations/20241206_seed_100_doctors.sql', sql);
console.log('Successfully generated SQL seed file with Women Health focus.');
