-- Seed Encyclopedia Content
-- Generated by script

-- Clear existing data if you want fresh start
-- TRUNCATE TABLE medical_conditions CASCADE;


DO $$
DECLARE
    new_id UUID := uuid_generate_v4();
BEGIN
    INSERT INTO medical_conditions (
        id, 
        name_en, 
        name_ar, 
        slug, 
        overview_ar, 
        symptoms_ar, 
        diagnosis_ar, 
        treatment_ar, 
        specialty,
        created_at
    )
    VALUES (
        new_id,
        'PCOS',
        'متلازمة تكيس المبايض',
        'pcos',
        'حالة هرمونية شائعة تؤثر على النساء في سن الإنجاب. تسبب عدم انتظام الدورة الشهرية وزيادة نمو الشعر.

الأسباب:
زيادة الأندروجين، مقاومة الأنسولين، عوامل وراثية.',
        'عدم انتظام الدورة الشهرية، زيادة الوزن، حب الشباب، نمو الشعر الزائد.',
        'فحص الحوض، الموجات فوق الصوتية، تحاليل الدم.',
        'تصحيح نمط الحياة، أدوية تنظيم الدورة، علاج الخصوبة.',
        'OB/GYN',
        now()
    );
EXCEPTION WHEN unique_violation THEN NULL;
END $$;

DO $$
DECLARE
    new_id UUID := uuid_generate_v4();
BEGIN
    INSERT INTO medical_conditions (
        id, 
        name_en, 
        name_ar, 
        slug, 
        overview_ar, 
        symptoms_ar, 
        diagnosis_ar, 
        treatment_ar, 
        specialty,
        created_at
    )
    VALUES (
        new_id,
        'Endometriosis',
        'بطانة الرحم المهاجرة',
        'endometriosis',
        'حالة ينمو فيها نسيج مشابه لبطانة الرحم خارج الرحم، مما يسبب ألماً شديداً ومشاكل في الخصوبة.

الأسباب:
غير معروفة بدقة، قد تشمل الحيض الرجعي والعوامل الوراثية.',
        'ألم الحوض المزمن، ألم شديد أثناء الدورة، ألم أثناء الجماع.',
        'تنظير البطن، الفحص السريري، الرنين المغناطيسي.',
        'مسكنات الألم، العلاج الهرموني، الجراحة.',
        'OB/GYN',
        now()
    );
EXCEPTION WHEN unique_violation THEN NULL;
END $$;

DO $$
DECLARE
    new_id UUID := uuid_generate_v4();
BEGIN
    INSERT INTO medical_conditions (
        id, 
        name_en, 
        name_ar, 
        slug, 
        overview_ar, 
        symptoms_ar, 
        diagnosis_ar, 
        treatment_ar, 
        specialty,
        created_at
    )
    VALUES (
        new_id,
        'Gestational Diabetes',
        'سكري الحمل',
        'gestational-diabetes',
        'ارتفاع سكر الدم الذي يتطور أثناء الحمل ويختفي عادة بعد الولادة.

الأسباب:
التغيرات الهرمونية أثناء الحمل التي تؤثر على عمل الأنسولين.',
        'زيادة العطش، التبول المتكرر، التعب.',
        'اختبار تحمل الجلوكوز الفموي.',
        'مراقبة سكر الدم، نظام غذائي صحي، الأنسولين إذا لزم الأمر.',
        'OB/GYN',
        now()
    );
EXCEPTION WHEN unique_violation THEN NULL;
END $$;

DO $$
DECLARE
    new_id UUID := uuid_generate_v4();
BEGIN
    INSERT INTO medical_conditions (
        id, 
        name_en, 
        name_ar, 
        slug, 
        overview_ar, 
        symptoms_ar, 
        diagnosis_ar, 
        treatment_ar, 
        specialty,
        created_at
    )
    VALUES (
        new_id,
        'Postpartum Depression',
        'اكتئاب ما بعد الولادة',
        'postpartum-depression',
        'نوع من الاكتئاب يحدث بعد الولادة، يتجاوز كآبة النفاس العادية ويؤثر على القدرة على العناية بالطفل.

الأسباب:
انخفاض حاد في الهرمونات بعد الولادة، الحرمان من النوم، الضغوط النفسية.',
        'تقلبات مزاجية حادة، انسحاب من العائلة، صعوبة في الارتباط بالطفل.',
        'تقييم نفسي شامل.',
        'العلاج النفسي، مضادات الاكتئاب.',
        'Mental Health',
        now()
    );
EXCEPTION WHEN unique_violation THEN NULL;
END $$;

DO $$
DECLARE
    new_id UUID := uuid_generate_v4();
BEGIN
    INSERT INTO medical_conditions (
        id, 
        name_en, 
        name_ar, 
        slug, 
        overview_ar, 
        symptoms_ar, 
        diagnosis_ar, 
        treatment_ar, 
        specialty,
        created_at
    )
    VALUES (
        new_id,
        'UTI',
        'التهاب المسالك البولية',
        'uti',
        'عدوى تصيب أي جزء من الجهاز البولي، وهي أكثر شيوعاً لدى النساء.

الأسباب:
بكتيريا تدخل مجرى البول.',
        'حرقان أثناء التبول، حاجة ملحة للتبول، ألم في الحوض.',
        'تحليل البول.',
        'المضادات الحيوية، شرب الكثير من السوائل.',
        'General Practice',
        now()
    );
EXCEPTION WHEN unique_violation THEN NULL;
END $$;

DO $$
DECLARE
    new_id UUID := uuid_generate_v4();
BEGIN
    INSERT INTO medical_conditions (
        id, 
        name_en, 
        name_ar, 
        slug, 
        overview_ar, 
        symptoms_ar, 
        diagnosis_ar, 
        treatment_ar, 
        specialty,
        created_at
    )
    VALUES (
        new_id,
        'Breast Cancer',
        'سرطان الثدي',
        'breast-cancer',
        'سرطان يتشكل في خلايا الثدي. الكشف المبكر يزيد بشكل كبير من فرص الشفاء.

الأسباب:
طفرات جينية (BRCA)، التقدم في العمر، التاريخ العائلي.',
        'كتلة في الثدي، تغير في شكل الثدي، إفرازات غير طبيعية.',
        'الماموجرام، الموجات فوق الصوتية، الخزعة.',
        'الجراحة، العلاج الكيماوي، العلاج الإشعاعي.',
        'General Practice',
        now()
    );
EXCEPTION WHEN unique_violation THEN NULL;
END $$;

DO $$
DECLARE
    new_id UUID := uuid_generate_v4();
BEGIN
    INSERT INTO medical_conditions (
        id, 
        name_en, 
        name_ar, 
        slug, 
        overview_ar, 
        symptoms_ar, 
        diagnosis_ar, 
        treatment_ar, 
        specialty,
        created_at
    )
    VALUES (
        new_id,
        'Menopause',
        'انقطاع الطمث',
        'menopause',
        'نهاية الدورة الشهرية بشكل طبيعي، عادة في سن 45-55.

الأسباب:
انخفاض طبيعي في الهرمونات التناسلية.',
        'هبات ساخنة، تعرق ليلي، تقلبات مزاجية، جفاف مهبلي.',
        'فحص الدم لمستويات الهرمونات (FSH).',
        'العلاج الهرموني التعويضي، تغييرات نمط الحياة.',
        'OB/GYN',
        now()
    );
EXCEPTION WHEN unique_violation THEN NULL;
END $$;

DO $$
DECLARE
    new_id UUID := uuid_generate_v4();
BEGIN
    INSERT INTO medical_conditions (
        id, 
        name_en, 
        name_ar, 
        slug, 
        overview_ar, 
        symptoms_ar, 
        diagnosis_ar, 
        treatment_ar, 
        specialty,
        created_at
    )
    VALUES (
        new_id,
        'Fibroids',
        'الألياف الرحمية',
        'fibroids',
        'أورام غير سرطانية في الرحم تظهر غالباً خلال سنوات الإنجاب.

الأسباب:
تغيرات جينية، هرمونات (استروجين وبروجسترون).',
        'نزيض حيض غزير، ألم في الحوض، تكرار التبول.',
        'الموجات فوق الصوتية، الرنين المغناطيسي.',
        'الأدوية، الجراحة (استئصال الورم أو الرحم).',
        'OB/GYN',
        now()
    );
EXCEPTION WHEN unique_violation THEN NULL;
END $$;
